name: "Publish Code Coverage"

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Deploy coverage to codecov
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Check PHP Version
        run: php --version

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Code Coverage Check
        uses: sourcetoad/phpunit-coverage-action@v1
        with:
          clover_report_path: coverage.xml
          min_coverage_percent: 80
          fail_build_on_under: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml
          fail_ci_if_error: false